FROM node:18-alpine AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app

COPY package.json yarn.lock ./
RUN  yarn install

FROM node:18-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

ARG NEXT_PUBLIC_POLYGON_SCAN_API_KEY
ENV NEXT_PUBLIC_POLYGON_SCAN_API_KEY=$NEXT_PUBLIC_POLYGON_SCAN_API_KEY

ARG NEXT_PUBLIC_ETHER_SCAN_API_KEY
ENV NEXT_PUBLIC_ETHER_SCAN_API_KEY=$NEXT_PUBLIC_ETHER_SCAN_API_KEY

ARG NEXT_PUBLIC_POLYGON_SCAN_BASE_URL_TESTNET
ENV NEXT_PUBLIC_POLYGON_SCAN_BASE_URL_TESTNET=$NEXT_PUBLIC_POLYGON_SCAN_BASE_URL_TESTNET

ARG NEXT_PUBLIC_POLYGON_SCAN_BASE_URL
NEXT_PUBLIC_POLYGON_SCAN_BASE_URL=$NEXT_PUBLIC_POLYGON_SCAN_BASE_URL

ARG NEXT_PUBLIC_ETHER_SCAN_BASE_URL
ENV NEXT_PUBLIC_ETHER_SCAN_BASE_URL=$NEXT_PUBLIC_ETHER_SCAN_BASE_URL

ARG NEXT_PUBLIC_PROVIDER_URL
ENV NEXT_PUBLIC_PROVIDER_URL=$NEXT_PUBLIC_PROVIDER_URL

ARG NEXT_PUBLIC_PROVIDER_URL_TESTNET
ENV NEXT_PUBLIC_PROVIDER_URL_TESTNET=$NEXT_PUBLIC_PROVIDER_URL_TESTNET

ARG NEXT_PUBLIC_ENVIRONMENT
ENV NEXT_PUBLIC_ENVIRONMENT=$NEXT_PUBLIC_ENVIRONMENT

ENV NEXT_TELEMETRY_DISABLED 1

RUN yarn build

FROM node:18-alpine AS runner
WORKDIR /app

ENV NODE_ENV production
ENV NEXT_TELEMETRY_DISABLED 1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder --chown=nextjs:nodejs /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json

USER nextjs

EXPOSE 3000

ENV PORT 3000

CMD ["npm", "start"]
